PulchowkHub/App1/urls.py
from django.conf.urls import url
from App1 import views
app_name = 'App1'
urlpatterns=[
    url('registration/',views.registration,name = 'registration'),
    url('user_login/',views.user_login,name='user_login'),
    url('contactpage/',views.contactpage,name = 'contactpage'),
    ]

PulchowkHub/PulchowkHub/urls.py
from django.contrib import admin
from django.urls import path,include
from App1 import models,views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name = 'index'),
    path('App1/',include('App1.urls')),
    path('user_logout/',views.user_logout,name= 'user_logout'),
    path('special/',views.special,name='special'),
    
]

PulchowkHub/App1/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete = models.CASCADE)
    portfolio_site = models.CharField(max_length=264,blank=True)
    profile_pic = models.ImageField(upload_to = 'Profile_Pictures', blank = True)

    def __str__(self):
        return self.user.username

PulchowkHub/App1/forms.py
from django import forms
from django.contrib.auth.models import User
from App1.models import UserProfileInfo

class UserInfo(forms.ModelForm):

    password = forms.CharField(widget = forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields=('portfolio_site','profile_pic')

PulchowkHub/App1/views.py
from django.shortcuts import render,redirect
from App1.forms import UserInfo,UserProfileInfoForm

#Import for login

from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required



# Create your views here.
def contactpage(request):
    return render(request,'App1/contactpage.html')

def index(request):
    return render(request,'App1/index.html')

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username = username,password =password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("Account not active")

        else:
            print('Login Failed')
            print("username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login")

    else:
        return render(request,"App1/login.html",{})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponse("You are logged in!!")



def registration(request):
     registered = False

     if request.method == "POST":
         user_form = UserInfo(data = request.POST)
         profile_form = UserProfileInfoForm(data = request.POST)

         if user_form.is_valid() and profile_form.is_valid():
             user = user_form.save()
             user.set_password(user.password)
             user.save()

             profile = profile_form.save(commit = False)
             profile.user = user

             if 'profile_pic' in request.FILES:
                 profile.profile_pic= request.FILES['profile_pic']
             profile.save()
             registered = True
         else:
            print(user_form.errors,profile_form.errors)

     else:
         user_form = UserInfo()
         profile_form = UserProfileInfoForm()
     return render(request,'App1/register.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})

PulchowkHub/templates/App1/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="css/mystyle.css" type="text/css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class ="navbar navbar-default navbaar-static-top">
    <div class="container">
      <ul class= "nav navbar-nav">
        <li><a class ="navbar-brand" href="{% url 'index' %}">PulchowkHub</a></li>
        <li><a class = "navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
        <li><a class = "navbar-link" href="{% url 'App1:registration' %}">Register Here</a></li>
        <li><a class = "navbar-link" href="{% url 'App1:contactpage' %}">Contact Us</a></li>
        {% if user.is_authenticated %}
        <li><a class ="navbar-link" href="{% url 'user_logout' %}">Logout</a></li>
        {% else %}
        <li><a class = "navbar-link" href="{% url 'App1:user_login' %}">Login</a></li>
        {% endif %}
        {% block body_block %}
        {% endblock %}
  </body>
</html>

PulchowkHub/templates/App1/contactpage.html
<!DOCTYPE html>
{% extends 'App1/base.html'%}
{% block body_block %}
<div class="contact">
  <div class="jumbotron">
  <h1>This is the contact page!!!</h1>
  </div>
</div>
{% endblock %}

PulchowkHub/templates/App1/index.html
<!DOCTYPE html>

{% extends "App1/base.html" %}

{% block body_block %}
  <h1>This is homepage</h1>
{% endblock %}

PulchowkHub/templates/App1/login.html
<!DOCTYPE html>
{% extends "App1/base.html" %}

{% block body_block %}
<div class="jumbotron">
  <h1>Login Here!!</h1>
  <form  action="{% url 'App1:user_login'%}" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter your username">
    <label for="password">Password:</label>
    <input type="password" name="password">
    <input type="submit" value="Login">
  </form>
</div>
{% endblock %}

PulchowkHub/templates/App1/register.html
<!DOCTYPE html>
{% extends "App1/base.html" %}
{% load static %}

{% block body_block %}

 <div class="jumbotron">
  {% if registered %}
    <h1>Thank u for registering</h1>
  {% else %}
    <h1>Register here!!!</h1>
    <h3>Fill out the following form:</h3>
    <form enctype="multipart/form-data" method="post">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <input type="submit"  value="Register">
    </form>
 </div>
  {% endif %}
 {% endblock %}